### ISSUE TITLE
throw WebServiceException when http post success

### ISSUE THREAD

**Issue by twolight** [SmartDengg/android-easy-cleanarchitecture#1]
In one case，http post not return data，just return code and message.

```
@Override public Flowable<Model> filterWebServiceErrors() {
    if (RESULT_OK.equals(error_code) && null != data) {
      return Flowable.just(data);
    } else {
      return Flowable.error(new WebServiceException(reason));
    }
  }
```
post success but  throw WebServiceException

**Comment by SmartDengg** [comment]
This is some code examples, and does not guarantee the correct running, I also recommend that the combination of blog to understand, rather than simply run.
